# Default values for kubekubevirt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceSubnet: 10.96.0.0/12
podSubnet: 172.16.0.0/16

storageClass:

# Deploy haproxy to load-balance the Kubernetes API endpoint
# This is required if using more than 1 control-plane node
haproxy:
  enabled: true

controlPlane:
  count: 1
  memory: 16384M
  disk:
    capacity: 100Gi

worker:
  count: 1
  memory: 16384M
  disk:
    capacity: 100Gi

ingress:
  enabled: false
  className: ""
  annotations: {}
    # You will need to indicate that the service is TLS
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # or
    # haproxy.org/server-ssl: "true"
    # or equivalent
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}
