apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubekubevirt.fullname" . }}
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
data:
  kubeadm.yaml: |-
    ---
    kind: InitConfiguration
    apiVersion: kubeadm.k8s.io/v1beta4
    localAPIEndpoint:
      bindPort: 6443
    ---
    kind: ClusterConfiguration
    apiVersion: kubeadm.k8s.io/v1beta4
    kubernetesVersion: v1.32.5
    controlPlaneEndpoint: {{ include "kubekubevirt.fullname" . }}:6443
    networking:
      serviceSubnet: {{ .Values.serviceSubnet }}
      podSubnet: {{ .Values.podSubnet }}
    certificatesDir: /etc/kubernetes/pki
    etcd:
      local:
        dataDir: /var/lib/etcd
    ---
    kind: KubeletConfiguration
    apiVersion: kubelet.config.k8s.io/v1beta1
    cgroupDriver: systemd
    maxPods: 110
    serverTLSBootstrap: true
    ---
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    mode: ipvs
    ipvs:
      strictARP: true
  parse-kubeadm-init.py: |-
    import re
    import sys


    for line in sys.stdin:
        if "initialized successfully" in line:
            break
    else:
        sys.exit(1)

    join_command = []

    for line in sys.stdin:
        if re.search(r'\bkubeadm join\b', line):
            join_command.append(line.strip().rstrip('\\').rstrip())
            break
    else:
        sys.exit(1)

    for line in sys.stdin:
        line = line.strip()
        if not line:
            break
        join_command.append(line.rstrip('\\').rstrip())

    print(' '.join(join_command))
  run.sh: |-
    ourname="$(hostname | sed 's/^.*\(\(controlplane\|worker\)-[0-9]*\)$/\1/')"
    ourkind="$(hostname | sed 's/^.*\(controlplane\|worker\)-[0-9]*$/\1/')"
    if [ "$ourname" = "controlplane-0" ]; then
      exec bash /etc/kubekubevirt/setup.sh
    elif [ "$ourkind" = "controlplane" ]; then
      exec bash /etc/kubekubevirt/join-controlplane.sh
    elif [ "$ourkind" = "worker" ]; then
      exec bash /etc/kubekubevirt/join-worker.sh
    fi
    exit 1
  setup.sh: |-
    if ! kubeadm init --config /etc/kubekubevirt/kubeadm.yaml --upload-certs > /root/kubeadm-init.log 2>&1; then
      cat /root/kubeadm-init.log
      exit 1
    fi
    python3 /etc/kubekubevirt/parse-kubeadm-init.py < /root/kubeadm-init.log > /root/join-controlplane.command.new || exit 1
    mv /root/join-controlplane.command.new /root/join-controlplane.command || exit 1
    sed 's/ --control-plane//; s/ --certificate-key[ =][^ ]\+//' < /root/join-controlplane.command > /root/join-worker.command.new
    mv /root/join-worker.command.new /root/join-worker.command
    # TODO: Upload the command as a secret with kubectl
    # install calico
    # install kubelet-csr-approver
  join-controlplane.sh: |-
    apt-get update && apt-get install -yy sshpass # TODO: bake into image
    while true; do
      JOIN_COMMAND="$(sshpass -f/etc/kubekubevirt-secrets/ssh_password ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@{{ include "kubekubevirt.fullname" . }}-setup "sudo cat /root/join-controlplane.command")"
      if [ $? = 0 ]; then
        exec $JOIN_COMMAND > /root/kubeadm-join.log 2>&1
        exit 1
      fi
      sleep 10
    done
