{{- range $vmIndex := until (.Values.controlPlane.count | int) }}
{{- with $ }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-controlplane-{{ $vmIndex }}
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.controlPlane.disk.capacity }}
  {{- if ne .Values.storageClass nil }}
  storageClassName: {{ .Values.storageClass | quote }}
  {{- end }}
  volumeMode: Block
  dataSource:
    kind: PersistentVolumeClaim
    name: {{ include "kubekubevirt.fullname" . }}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-controlplane-{{ $vmIndex }}
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
    tier: controlplane
spec:
  running: true
  template:
    metadata:
      labels:
        {{- include "kubekubevirt.labels" . | nindent 8 }}
        tier: controlplane
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: disk
            - disk:
                bus: virtio
              name: cloudinit
          filesystems:
            - name: config
              virtiofs: {}
            - name: secrets
              virtiofs: {}
          interfaces:
            - bridge: {}
              name: default
        cpu:
          sockets: 2
          cores: 4
          threads: 1
        machine:
          type: q35
        resources:
          requests:
            memory: {{ .Values.controlPlane.memory }}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: disk
          persistentVolumeClaim:
            claimName: {{ include "kubekubevirt.fullname" . }}-controlplane-{{ $vmIndex }}
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: {{ include "kubekubevirt.fullname" . }}-cloudinit
        - name: config
          configMap:
            name: {{ include "kubekubevirt.fullname" . }}
        - name: secrets
          secret:
            secretName: {{ include "kubekubevirt.fullname" . }}-ssh
{{- end }}
{{- end }}
