apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ include "kubekubevirt.fullname" . }}
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
spec:
  storage:
    resources:
      requests:
        storage: 5Gi
    {{- if ne .Values.storageClass nil }}
    storageClassName: {{ .Values.storageClass | quote }}
    {{- end }}
  source:
    registry:
      url: "docker://ghcr.io/remram44/kubekubevirt:ubuntu-24.04-1.32.5-20250630t232927z"
