apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ include "kubekubevirt.fullname" . }}
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storage:
    resources:
      requests:
        storage: 6Gi
    {{- if ne .Values.storageClass nil }}
    storageClassName: {{ .Values.storageClass | quote }}
    {{- end }}
  source:
    registry:
      url: "docker://ghcr.io/remram44/kubekubevirt-vm:ubuntu-24.04-kubernetes-1.35.7-20260817t194544z"
