{{- range $vmIndex := until (.Values.worker.count | int) }}
{{- with $ }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-join-worker-{{ $vmIndex }}
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
    tier: worker
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create
          image: python:3.12
          args:
            - sh
            - -c
            - |-
              USER=ubuntu
              PASSWORD="$(cat /etc/kubekubevirt/ssh_password)"
              HOST={{ include "kubekubevirt.fullname" . }}-worker-{{ $vmIndex }}
              # TODO: SSH into controlplane-0 to get credentials
              # TODO: SSH into worker-$vmIndex and join cluster with kubeadm
          volumeMounts:
            - mountPath: /etc/kubekubevirt
              name: secret
      volumes:
        - name: secret
          secret:
            secretName: {{ include "kubekubevirt.fullname" . }}-ssh
{{- end }}
{{- end }}
