apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-create
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
    tier: controlplane
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create
          image: python:3.12
          args:
            - sh
            - -c
            - "true"
            #- |-
            #  USER=ubuntu
            #  HOST={{ include "kubekubevirt.fullname" . }}-controlplane-0
            #  SCRIPT="$(printf 'sudo kubeadm init --config /etc/kubekubevirt/config/kubeadm.yaml --node-name %s --upload-certs\n' $HOST)"
            #  OUTPUT="$(sshpass -f /etc/kubekubevirt/secrets/ssh_password $USER@$HOST "$SCRIPT")"
            #  if [ $? != 0 ]; then exit 1; fi
          volumeMounts:
            - mountPath: /etc/kubekubevirt/config
              name: config
            - mountPath: /etc/kubekubevirt/secrets
              name: secret
      volumes:
        - name: config
          configMap:
            name: {{ include "kubekubevirt.fullname" . }}
        - name: secret
          secret:
            secretName: {{ include "kubekubevirt.fullname" . }}-ssh
