{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-ssh" (include "kubekubevirt.fullname" .))) | default dict }}
{{- $password := (get (get $secret "data" | default dict) "ssh_password") | default (randAlphaNum 32 | b64enc) -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-ssh
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
data:
  ssh_password: {{ $password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-cloudinit
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
stringData:
  userdata: |-
    #cloud-config
    password: {{ $password | b64dec | quote }}
    chpasswd:
      expire: false
    ssh_pwauth: true
    runcmd:
      - ["/bin/bash", "-c", "mkdir -p /etc/kubekubevirt && mount -t virtiofs config /etc/kubekubevirt && mkdir -p /run/secrets/kubernetes.io/serviceaccount && mount -t virtiofs serviceaccount /run/secrets/kubernetes.io/serviceaccount && exec bash /etc/kubekubevirt/run.sh"]
