{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "kubekubevirt.fullname" .)) | default dict }}
{{- $password := (get (get $secret "data" | default dict) "ssh_password") | default (randAlphaNum 32 | b64enc) -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-ssh
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
data:
  ssh_password: {{ $password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-cloudinit
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
stringData:
  userdata: |-
    #cloud-config
    password: {{ $password | b64dec | quote }}
    chpasswd:
      expire: false
    ssh_pwauth: true
