apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-setup
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    vm.kubevirt.io/name: {{ include "kubekubevirt.fullname" . }}-controlplane-0
  ports:
    - name: https
      port: 6443
      protocol: TCP
      targetPort: 6443
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
