apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubekubevirt.fullname" . }}
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "kubekubevirt.selectorLabels" . | nindent 4 }}
    tier: controlplane
  ports:
    - name: https
      port: 6443
      protocol: TCP
      targetPort: 6443
