{{- range $vmIndex := until (.Values.worker.count | int) }}
{{- with $ }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-worker-{{ $vmIndex }}
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.worker.disk.capacity }}
  {{- if ne .Values.storageClass nil }}
  storageClassName: {{ .Values.storageClass | quote }}
  {{- end }}
  volumeMode: Block
  dataSource:
    kind: PersistentVolumeClaim
    name: {{ include "kubekubevirt.fullname" . }}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "kubekubevirt.fullname" . }}-worker-{{ $vmIndex }}
  labels:
    {{- include "kubekubevirt.labels" . | nindent 4 }}
    tier: worker
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        {{- include "kubekubevirt.labels" . | nindent 8 }}
        tier: worker
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: disk
            - disk:
                bus: virtio
              name: cloudinit
          filesystems:
            - name: config
              virtiofs: {}
            - name: serviceaccount
              virtiofs: {}
          interfaces:
            - bridge: {}
              name: default
        cpu:
          sockets: 2
          cores: 4
          threads: 1
        machine:
          type: q35
        resources:
          requests:
            memory: {{ .Values.worker.memory }}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: disk
          persistentVolumeClaim:
            claimName: {{ include "kubekubevirt.fullname" . }}-worker-{{ $vmIndex }}
        - name: cloudinit
          cloudInitNoCloud:
            secretRef:
              name: {{ include "kubekubevirt.fullname" . }}-cloudinit
        - name: config
          configMap:
            name: {{ include "kubekubevirt.fullname" . }}
        - name: serviceaccount
          serviceAccount:
            serviceAccountName: {{ include "kubekubevirt.fullname" . }}
{{- end }}
{{- end }}
